Repository midnight-machinations/midnight-machinations, pull requests merged in 2025-03, with the labels that each got.

#777 switch to pnpm and add devcontainer.json
  .devcontainer/devcontainer.json
  client/package-lock.json
  client/package.json
  client/pnpm-lock.yaml
  client/src/components/gameModeSettings/GameModesEditor.tsx
  client/src/index.tsx
  client/src/menu/Anchor.tsx
  server/Cargo.toml
Labels: High Priority

#778 Serial Killer fix. Better code readability for several roles
  server/src/game/role/drunk.rs
  server/src/game/role/jailor.rs
  server/src/game/role/kidnapper.rs
  server/src/game/role/ojo.rs
  server/src/game/role/recruiter.rs
  server/src/game/role/reeducator.rs
  server/src/game/role/serial_killer.rs
Labels: Bug, Docs

#773 Tests & Idiot proofing for Yer
  client/src/resources/lang/en_us.json
  server/src/game/role/yer.rs
  server/tests/kit/mod.rs
  server/tests/role.rs
Labels: QoL

#776 Werewolf rework merge
  .vscode/settings.json
  client/src/components/ChatMessage.tsx
  client/src/resources/lang/en_us.json
  client/src/resources/roles.json
  client/src/resources/styling/chatMessage.json
  server/src/game/chat/chat_message_variant.rs
  server/src/game/components/night_visits.rs
  server/src/game/role/mod.rs
  server/src/game/role/werewolf.rs
  server/tests/role.rs
Labels: Balance or Rework

#786 Hidden Whisper Modifier
  client/src/game/gameState.d.tsx
  client/src/resources/lang/en_us.json
  server/src/game/modifiers/hidden_whispers.rs
  server/src/game/modifiers/mod.rs
  server/src/game/on_client_message.rs
  server/src/game/player/player_send_packet.rs
Labels: New Feature

#787 Added Skip Day 1 Modifier
  client/src/game/gameState.d.tsx
  client/src/resources/lang/en_us.json
  server/src/game/modifiers/mod.rs
  server/src/game/modifiers/skip_day_1.rs
Labels: New Feature

#767 Host Settings Menu
  client/src/components/useHooks.tsx
  client/src/game/gameManager.d.tsx
  client/src/game/gameManager.tsx
  client/src/game/gameState.d.tsx
  client/src/game/gameState.tsx
  client/src/game/messageListener.tsx
  client/src/game/packet.tsx
  client/src/menu/GlobalMenu.tsx
  client/src/menu/HostMenu.tsx
  client/src/menu/game/HeaderMenu.tsx
  client/src/menu/game/gameScreenContent/PlayerListMenu.tsx
  client/src/menu/lobby/LobbyMenu.tsx
  client/src/menu/lobby/LobbyPlayerList.tsx
  client/src/menu/lobby/lobbyMenu.css
  client/src/resources/lang/en_us.json
  server/src/game/game_conclusion.rs
  server/src/game/mod.rs
  server/src/game/phase.rs
  server/src/game/player/player_accessors.rs
  server/src/game/player/player_send_packet.rs
  server/src/game/spectator/spectator_pointer.rs
  server/src/lobby/game_client.rs
  server/src/lobby/mod.rs
  server/src/lobby/name_validation.rs
  server/src/lobby/on_client_message.rs
  server/src/packet.rs
Labels: New Feature

#797 Pseudo enabled roles
  .vscode/settings.json
  server/src/game/mod.rs
  server/src/game/role/doomsayer.rs
  server/src/game/role/mod.rs
Labels: Meta
